### ISSUE TITLE
What is the font used in the example image?

### ISSUE THREAD

**Issue by ghost** [catppuccin/fish#1]
<p align="center">
  <img src="https://raw.githubusercontent.com/catppuccin/fish/main/assets/ss.png"/>
</p>

**Comment by guangxu-li** [comment]
Any chance that u found out the answer? It looks gorgeous.

**Comment by andres2004u** [comment]
@guangxu-li No Bro, but, it is similar to Cartograph CF. Maybe it's that. 😎🌟

**Comment by guangxu-li** [comment]
> @guangxu-li No Bro, but, it is similar to Cartograph CF. Maybe it's that. sunglassesstar2

![image](https://user-images.githubusercontent.com/15380843/173222167-62cd028a-35d6-4703-872a-d334d19c013f.png)

Configured Cartograph CF with style set 'ss01', it's indeed close to the font in the screenshot.
