### ISSUE TITLE
No such subcommand: theme

### ISSUE THREAD

**Issue by glendell03** [catppuccin/fish#12]
I can't save theme using this command `fish_config theme save "Catppuccin Mocha"`
![image](https://user-images.githubusercontent.com/58845052/205257918-e1f99384-2860-449c-866e-f3f8f05197f8.png)

**Comment by hugginsio** [comment]
Can you share the output of `fish --version`? You may be using an older version of fish.

**Comment by Plokil** [comment]
Doing `sudo apt install fish` on its own will install old version of fish.
To install new fish version do:
$ `sudo apt-add-repository ppa:fish-shell/release-3`
$ `sudo apt update`
$ `sudo apt install fish`
And then execute `fish_config theme save "Catppuccin Mocha"` to apply the theme
