### ISSUE TITLE
Add new manual instructions for fish >= 3.4.0

### ISSUE THREAD

**Issue by eight85** [catppuccin/fish#14]
Fish >= 3.4.0 requires you to add this line when manually adding the catppuccin theme. Otherwise the theme won't persist and default back to the main theme once you close your terminal. Consider adding the following to the fish.config in .config/fish/config.fish at the first line. Example Catppuccin Mocha theme.

`fish_config theme choose "Catppuccin Mocha"`

**Comment by ghostx31** [comment]
The correct installation instructions have been added in README so closing this.
