### ISSUE TITLE
[Question] How to colorize result of ls -la command like example picture?

### ISSUE THREAD

**Issue by RAVENz46** [catppuccin/fish#18]
Do I need additional plugins or something?

[ My env ]
OS: NixOS-unstable
Terminal Emulator: WezTerm/Konsole
fish version: 3.6.1

echo $TERM returns xterm-256color

**Comment by ghostx31** [comment]
Its a program called [eza](https://github.com/eza-community/eza). You can create alias for ls` which actually calls `eza`.

**Comment by RAVENz46** [comment]
@ghostx31 Thank you!
