### ISSUE TITLE
after OMF installation not possible to revert?

### ISSUE THREAD

**Issue by dinotheextinct** [catppuccin/fish#2]
I installed this plugin through OMF and now I cant change my colorscheme anymore through fish_config?

**Comment by dinotheextinct** [comment]
Amazing, it seems your weird OMF installation install into the default OMF theme...*golfclap*

**Comment by nekowinston** [comment]
Should also be closed with https://github.com/catppuccin/fish/commit/48a3cb42b6d575ce20c5dd3cfc97877ba8a8eba4
