### ISSUE TITLE
Documentation Note

### ISSUE THREAD

**Issue by bdmorin** [catppuccin/fish#4]
No bug, but the install from fisher and omf install all the themes in `conf.d`, but the shell will only take the last one. (i'm pretty sure by sorted by filename)
```bash
ls -1 .config/fish/conf.d/
abbrfile.fish
frappe.fish
latte.fish
macchiato.fish
mocha.fish
omf.fish
xdg.fish
```
so - in this case, the theme that picks up is `mocha.fish`. Less experienced users may not understand how to use `frappe`, or `latte`. 

So, a user would rename the one they want to like `z_latte.fish` or something if they wanted it to be active.

**Comment by lvignoli** [comment]
I concur on this issue. Fish's [docs](https://fishshell.com/docs/current/language.html#configuration-files) specified that the execution order is sorted by natural order, so glob like.

Hence fish load 4 files to only retain the colorscheme of the last one, `mocha.fish`.

How difficult would it be to provide a mechanism to source only one of the four color scheme? I have no idea on how this situation is handled by other fisher plugins.

**Comment by nekowinston** [comment]
This should also be closed with https://github.com/catppuccin/fish/commit/48a3cb42b6d575ce20c5dd3cfc97877ba8a8eba4, since we're using `.theme` instead of fish now. Please re-open, if I'm mistaken.
