### ISSUE TITLE
How are you supposed to install this?

### ISSUE THREAD

**Issue by JimmyMinhLee** [catppuccin/fish#5]
Saw the theme and was able to set it up on all my other software tools, but I can't seem to get it usable with iTerm2 & Fish Shell. I assume it's because I've previously used `omf` and `tide`. Is there any step by step instructions available? The theme is too cute to pass up on!

**Comment by nekowinston** [comment]
Hopefully closed with https://github.com/catppuccin/fish/commit/48a3cb42b6d575ce20c5dd3cfc97877ba8a8eba4. Please check out the README again 😄
