### ISSUE TITLE
How to select a specific variant

### ISSUE THREAD

**Issue by guilhermedeandrade** [catppuccin/fish#7]
Just installed the fish theme using fisher and I've realized that 4 files (one per variant) is added to the `conf.d` folder. However, it would be nice to have instructions on how to select the variant you want.

If I'm not mistaken, all functions inside the `conf.d` are ran before your `config.fish`, right? Considering that this is right, should we delete the functions of the variants we don't want? For instance, if I want the Mocha variant, I need to delete `conf.d/latte.fish`, `conf.d/frappe.fish` and `conf.d/macchiato.fish`?

**Comment by caarlos0** [comment]
yeap, that sounds about right. Themes should probably be exported as proper themes as well, if there's interest, I can PR it..

**Comment by guilhermedeandrade** [comment]
> Themes should probably be exported as proper themes as well

I'd love to contribute, even though I don't have experience with fish plugins. However, do you mind explaining what you mean by this?

**Comment by nekowinston** [comment]
I hope this is closed with https://github.com/catppuccin/fish/commit/48a3cb42b6d575ce20c5dd3cfc97877ba8a8eba4 ?
Please do re-open if needed, I don't use fish myself.

**Comment by heygarrett** [comment]
It still doesn't seem clear how to choose a theme since all four of them get put in `~/.config/fish/themes/` when installing with fisher. Am I missing something?
